### ISSUE TITLE
Pdf-renderer tess4 looses DPI Info with any image-preprocessing.

### ISSUE THREAD

**Issue by 17Halbe** [jbarlow83/OCRmyPDF#147]
Hi there,

A (with a Fujitsu ScanSnap) scanned 600 dpi not ocr'd pdf wich is preprocessed with any of the preprocessing parameters (I tried -c, -r, -d, --oversample DPI and --remove-background) will get a Tesseract error of:

`INFO -    1: [tesseract] Warning. Invalid resolution 0 dpi. Using 70 instead.`

This is happening on the jbarlow83/ocrmypdf-tess4 docker image.
exact commandline:
`ocrmypdf -l deu -c --pdf-renderer tess4 input.pdf output.pdf`
See also: [[Clarification request/bug?] "Warning. Invalid resolution 0 dpi. Using 70 instead." #649](https://github.com/tesseract-ocr/tesseract/issues/649)
and also a Tesseract Forums entry: [Invalid resolution 0 dpi. Using 70 instead.](https://groups.google.com/d/msg/tesseract-ocr/oM1YdE_IFjs/kcgygT-YEQAJ)

So it seems like the dpi Information is lost during the preprocessing  (unpaper(?)).

Anyone else? 

regards Alex

**Comment by jbarlow83** [comment]
Looks like unpaper was indeed responsible for discarding the DPI. It always has, but the loss of this information only matters to the tess4 renderer.

Fixed in 4.5.2.

**Comment by 17Halbe** [comment]
That was a quick one! Thanks again for your effort and that great piece of software you cobbled together!

**Comment by 17Halbe** [comment]
Somehow the automated build for the docker image ( jbarlow83/ocrmypdf-tess4) didn't kick in. Can you please build it manually? Thanks a lot!

**Comment by jbarlow83** [comment]
Alright, I gave it a kick in the pants and it looks like it's ready again.

On Sat, Mar 25, 2017 at 12:55 17Halbe <notifications@github.com> wrote:

Somehow the automated build for the docker image (
jbarlow83/ocrmypdf-tess4) didn't kick in. Can you please build it manually?
Thanks a lot!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jbarlow83/OCRmyPDF/issues/147#issuecomment-289235444>,
or mute the thread

**Comment by 17Halbe** [comment]
Further investigations! ;) 

Most of the problems solved, though, when using the --clean parameter I still get the error:
`   INFO -    1: [tesseract] Warning. Invalid resolution 0 dpi. Using 70 instead.`

Surprisingly (probably) using the --clean-final parameter everything works as expected.
I tested following additional parameters: 

- --rotate-pages(with a page to rotate), 
- --remove-background and
- --deskew

Haven't had time to test --oversample DPI (But I will... Stay tuned!)

**Comment by jbarlow83** [comment]
Could you provide a full command line that is still causing trouble?

Also please check that `ocrmypdf --version` is 4.5.2

**Comment by 17Halbe** [comment]
Oh, you are right. Docker pulled an update after you kicked it but it still shows 4.5.1. 
So either the versioning number somehow didn't made it into the docker image, or docker didn't build the new image.

`docker run --rm -v /myDir/:/home/docker ocrmypdf --version
4.5.1
`
Though docker pulled something new, because some errors went away. (Same PDF, same commandline)
The exact commandline is:
`docker run --rm -v /Homepool/Documents/Home-Folder/alex/No-Images/:/home/docker ocrmypdf -j 1 --tesseract-timeout 360 -l deu+eng -c --pdf-renderer tess4 -f input.pdf output.pdf`

**Comment by jbarlow83** [comment]
I double-checked that the latest image is 4.5.2. Perhaps you pulled the
latest image but didn't update the "ocrmypdf" tag?

The digest of the 4.5.2 image is
$ docker images --digests jbarlow83/ocrmypdf-tess4
jbarlow83/ocrmypdf-tess4 latest
sha256:fdc6203751c9e09691c1d003b72f4358bf84189862247a5449c10197fdc6f94a

**Comment by 17Halbe** [comment]
Yep, that was the problem. I'm fairly new to docker, so excuse my lack of knowledge! 

Can be closed!
