### ISSUE TITLE
Page has no images - skipping OCR

### ISSUE THREAD

**Issue by AEgit** [jbarlow83/OCRmyPDF#84]
When using OCRmyPDF I sometimes get the message "page has no images - skipping OCR". When I check the respective page, however, text is clearly present (i.e., it is not a blank page). I was just wondering what the cause of this behaviour was?

A demo file that demonstrates the issue can be donwloaded here:
https://app.box.com/s/62wimr14fdmedwf751oq5atebm3l9u5m

**Comment by jbarlow83** [comment]
It means that there is no raster content on the page. It is either text or
vector artwork.

Usually this means OCR is not wanted on that page because it was probably
produced digitally rather than scanned.

**Comment by AEgit** [comment]
Have you checked the PDF I uploaded?
It clearly contains text (but not OCRed one) - from you answer I deduce that the text has not properly been stored for OCRmyPDF to work on. Do I need to convert this file to a raster image and then convert it back to PDF to make it usable for OCRmyPDF?

**Comment by jbarlow83** [comment]
I looked at the file and it did not look an image. The short answer is this
is a safety check but in your case it's not doing what you expect.

I will download it and examine.

You can use the -f (--force-ocr) to ask ocrmypdf to OCR the file anyway.

**Comment by AEgit** [comment]
Ok, maybe I did not explain the problem properly. The script runs properly (with and without -f) and a new PDF file is generated. But it does not contain any OCRed text.

**Comment by jbarlow83** [comment]
Okay, I looked at the file. It had text converted to curves (this is sometimes done for printing if the printer has trouble with the font), so it's a vector file. With `--force-ocr` this file worked for me.

Also add the parameter `--pdf-renderer tesseract`, which does a better job on files with columns of text, provided you have also installed tesseract 3.04.01. 

There are two things that could cause it to produ
* If you have a version older than 4.2, the latest, when I fixed a similar bug
* If tesseract times out on OCR. You can try `--tesseract-timeout N` for N > 3 to budget more time for OCR. It took a minute on my 2013 desktop machine, but a much slower/older machine might need more time.

**Comment by AEgit** [comment]
Thanks for your help - I will try your suggestions. I had the version 4.2 running. As it was running in a virtual machine, to which I assigned just 2 CPU cores, this might have been the problem.

**Comment by AEgit** [comment]
Hmmm, I've tried it now, but still the same result. A new PDF file is produced, but the text has not be OCRed.

Just to confirm, that I did not make a mistake, here the exact commands that I've run and the output of the script, while it is running:

`ocrmypdf --force-ocr -v --pdf-renderer tesseract --tesseract-timeout 5 -l eng Wang2013_Test.pdf Wang2013_ocr.pdf
`
`Tasks which will be run:


Task enters queue = 'ocrmypdf.main.repair_pdf' 
  DEBUG - [{'pageno': 0, 'height_inches': Decimal('11.6944'), 'images': [], 'has_text': False, 'width_inches': Decimal('8.26389')}]
Completed Task = 'ocrmypdf.main.repair_pdf' 
Task enters queue = 'ocrmypdf.main.split_pages' 
Task enters queue = 'ocrmypdf.main.generate_postscript_stub' 
   INFO -    1: page has no images - skipping OCR
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.apcaoo5c/000001.page.pdf, /tmp/com.github.ocrmypdf.apcaoo5c/000001.skip.page.pdf)
Completed Task = 'ocrmypdf.main.split_pages' 
Task enters queue = 'ocrmypdf.main.orient_page' 
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.apcaoo5c/000001.skip.page.pdf, /tmp/com.github.ocrmypdf.apcaoo5c/000001.skip.oriented.pdf)
Completed Task = 'ocrmypdf.main.generate_postscript_stub' 
Completed Task = 'ocrmypdf.main.orient_page' 
Task enters queue = 'ocrmypdf.main.rasterize_with_ghostscript' 
Uptodate Task = 'ocrmypdf.main.rasterize_with_ghostscript'


WARNING:
        In Task 'ocrmypdf.main.rasterize_with_ghostscript':
        No jobs were run because no file names matched.
        Please make sure that the regular expression is correctly specified. 

Task enters queue = 'ocrmypdf.main.preprocess_deskew' 
Uptodate Task = 'ocrmypdf.main.preprocess_deskew'
Task enters queue = 'ocrmypdf.main.preprocess_clean' 
Uptodate Task = 'ocrmypdf.main.preprocess_clean'
Task enters queue = 'ocrmypdf.main.select_image_for_pdf' 
Uptodate Task = 'ocrmypdf.main.select_image_for_pdf'
Task enters queue = 'ocrmypdf.main.skip_page' 
Task enters queue = 'ocrmypdf.main.tesseract_ocr_and_render_pdf' 
Uptodate Task = 'ocrmypdf.main.tesseract_ocr_and_render_pdf'


WARNING:
        In Task 'ocrmypdf.main.tesseract_ocr_and_render_pdf':
        No jobs were run because no file names matched.
        Please make sure that the regular expression is correctly specified. 

  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.apcaoo5c/000001.skip.oriented.pdf, /tmp/com.github.ocrmypdf.apcaoo5c/000001.done.pdf)
Completed Task = 'ocrmypdf.main.skip_page' 
Task enters queue = 'ocrmypdf.main.merge_pages' 
  DEBUG - Final pages: /tmp/com.github.ocrmypdf.apcaoo5c/000001.done.pdf
/tmp/com.github.ocrmypdf.apcaoo5c/pdfa_def.ps
Completed Task = 'ocrmypdf.main.merge_pages' 
Task enters queue = 'ocrmypdf.main.copy_final' 
Completed Task = 'ocrmypdf.main.copy_final' 
  DEBUG - [{'pageno': 0, 'height_inches': Decimal('11.6944'), 'images': [], 'has_text': False, 'width_inches': Decimal('8.26389')}]`

**Comment by AEgit** [comment]
Am I doing something wrong or can you spot an issue in the script output? If not, it's probably (?) related to my machine. I'm running the script on Ubuntu 16.04, 64bit in a Virtual Machine (Virtualbox). OCRmyPDF was installed using pip3.

**Comment by jbarlow83** [comment]
You must not have ocrmypdf 4.2. The text string "page has no images - skipping OCR" is not in version 4.2. Check `pip3 freeze`

**Comment by AEgit** [comment]
Oh my god, you are totally right - I still have 4.1.2 (but I'm sure as hell, that I did an upgrade today). Well anyway, thanks and I'm very sorry for having caused so much trouble!

**Comment by AEgit** [comment]
Ok, I did an upgrade to version 4.2 (this time it worked for sure, as I checked afterwards with pip3 freeze), but the problem persists:

 ```
ocrmypdf --force-ocr -v --pdf-renderer tesseract --tesseract-timeout 5 -l eng Wang2013_Test.pdf Wang2013_ocr.pdf

________________________________________
Tasks which will be run:


Task enters queue = 'ocrmypdf.main.triage' 
  DEBUG - os.symlink(Wang2013_Test.pdf, /tmp/com.github.ocrmypdf.8inanhwp/Wang2013_Test.pdf)
Completed Task = 'ocrmypdf.main.triage' 
Task enters queue = 'ocrmypdf.main.repair_pdf' 
  DEBUG - [{'pageno': 0, 'height_inches': Decimal('11.6944'), 'has_text': False, 'images': [], 'width_inches': Decimal('8.26389')}]
Completed Task = 'ocrmypdf.main.repair_pdf' 
Task enters queue = 'ocrmypdf.main.split_pages' 
Task enters queue = 'ocrmypdf.main.generate_postscript_stub' 
WARNING -    1: page has no images - all vector content will be rasterized at 400 DPI, losing some resolution and likely increasing file size. Use --oversample to adjust the DPI.
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.8inanhwp/000001.page.pdf, /tmp/com.github.ocrmypdf.8inanhwp/000001.ocr.page.pdf)
Completed Task = 'ocrmypdf.main.split_pages' 
Task enters queue = 'ocrmypdf.main.orient_page' 
Completed Task = 'ocrmypdf.main.generate_postscript_stub' 
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.8inanhwp/000001.ocr.page.pdf, /tmp/com.github.ocrmypdf.8inanhwp/000001.ocr.oriented.pdf)
Completed Task = 'ocrmypdf.main.orient_page' 
Task enters queue = 'ocrmypdf.main.rasterize_with_ghostscript' 
Task enters queue = 'ocrmypdf.main.skip_page' 
Uptodate Task = 'ocrmypdf.main.skip_page'


WARNING:
        In Task 'ocrmypdf.main.skip_page':
        No jobs were run because no file names matched.
        Please make sure that the regular expression is correctly specified. 

  DEBUG - Rasterize 000001.ocr.oriented.pdf with pngmono
Completed Task = 'ocrmypdf.main.rasterize_with_ghostscript' 
Task enters queue = 'ocrmypdf.main.preprocess_deskew' 
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.8inanhwp/000001.page.png, /tmp/com.github.ocrmypdf.8inanhwp/000001.pp-deskew.png)
Completed Task = 'ocrmypdf.main.preprocess_deskew' 
Task enters queue = 'ocrmypdf.main.preprocess_clean' 
  DEBUG - os.symlink(/tmp/com.github.ocrmypdf.8inanhwp/000001.pp-deskew.png, /tmp/com.github.ocrmypdf.8inanhwp/000001.pp-clean.png)
Completed Task = 'ocrmypdf.main.preprocess_clean' 
Task enters queue = 'ocrmypdf.main.select_image_for_pdf' 
Completed Task = 'ocrmypdf.main.select_image_for_pdf' 
Task enters queue = 'ocrmypdf.main.tesseract_ocr_and_render_pdf' 
WARNING -    1: [tesseract]  took too long to OCR - skipping
Completed Task = 'ocrmypdf.main.tesseract_ocr_and_render_pdf' 
Task enters queue = 'ocrmypdf.main.merge_pages_ghostscript' 
  DEBUG - Final pages: /tmp/com.github.ocrmypdf.8inanhwp/000001.rendered.pdf
/tmp/com.github.ocrmypdf.8inanhwp/pdfa_def.ps
Completed Task = 'ocrmypdf.main.merge_pages_ghostscript' 
Task enters queue = 'ocrmypdf.main.copy_final' 
Completed Task = 'ocrmypdf.main.copy_final' 
   INFO - File claims to be PDF/A-2B
  DEBUG - [{'pageno': 0, 'height_inches': Decimal('11.6944'), 'has_text': False, 'images': [], 'width_inches': Decimal('8.26389')}]
```

**Comment by jbarlow83** [comment]
Don't worry about it. Every time someone submits an issue I learn something about how people are using the program, so it does help improve it.

**Comment by AEgit** [comment]
Hmmm, I don't want to be annoying, but even with the new version it did not work out for me (see above). Do you have any clues when looking at the output of the script? If not, I will assume that something is wrong with the installation (?) and try to proceed that way.

**Comment by jbarlow83** [comment]
WARNING -    1: [tesseract]  took too long to OCR - skipping  

Needs a longer --tesseract-timeout

**Comment by AEgit** [comment]
You are right! This time I set the timeout to 100 and it worked. Unfortunately, the output is not as I expected - all letters are separated by blank spaces (see: https://app.box.com/s/4mtnl1k4ut3eryepa0m72v1oaqjsxzpf), which means, that a search within the document for certain keyowrds is meaningless. Is this due to the forced output, or could we overcome this problem as well?

Thanks again for your help!

**Comment by jbarlow83** [comment]
PDF does not actually encode the space between words - from its history of basically being an output to send to a printer, it does not account for spaces. It's up to the PDF viewer to heuristically determine where the spaces are, so different viewers give different results. This causes problems on academic papers where the spacing can vary due to full justified text. You can't always get this right in any PDF.

That said, you could try `--output-type pdf` to skip ghostscript as long as you're okay with skipping PDF/A conversion. This bypasses an open Ghostscript bug that sometimes makes output text a little worse.

**Comment by AEgit** [comment]
Hmmm, I've tried that one as well. Doesn't seem to work - anway, thank you very much for your help! And thanks for this great tool - I wouldn't know what to do without it!
